### ISSUE TITLE
Issues with article “weechat + Tor + SASL”

### ISSUE THREAD

**Issue by ghost** [szorfein/szorfein.github.io#1]
Hello,

I've followed your tutorial step by step on a clean config and I've ran into two issues:

1. Strings `"${sec.data.freenodeMail}"` (mail, user and password) are interpreted as a string of characters, not a variable, including char `"`.
2. Connection thru Tor is not possible and result with the following error messages:
```
gnutls: the hostname in the certificate does NOT match "freenodeok2gncmy.onion"
gnutls: peer's certificate is trusted
irc: TLS handshake failed
irc: error: Error in the certificate.
irc: reconnecting to server in 10 minutes
```

**Comment by szorfein** [comment]
Hi, thx for issue. 
I will enhance this article.

The main problem is, before enable tor, we must first register a nickname on freenode (without tor) and only after, we can generate a ecdsa cert and activate SASL & tor on account.

If you alrealy have an account on freenode then it's easy, `ssl_verify` can be disable too.  

    /set irc.server.freenode.ssl_verify off

**Comment by szorfein** [comment]
article enhance, hope it will help, thx :+1:
