### ISSUE TITLE
"/msg nickserv set private on" on tor/weechat page.

### ISSUE THREAD

**Issue by RealKindOne** [szorfein/szorfein.github.io#5]
https://szorfein.github.io/weechat/tor/configure-weechat/

On freenode ` ` ` HIDEMAIL` ` ` (hide email address from users) has been enabled by default for well over a decade when registering accounts so setting ` ` ` PRIVATE` ` `  on would only obscure the last seen / user seen dates of users in the ` ` ` /ns info foobar` ` ` 

` ` ` <NickServ> Last seen  : (about 52 weeks ago)` ` ` 

` ` ` <NickServ> User seen  : (about 0 weeks ago)` ` `

**Comment by szorfein** [comment]
Well, after a short research [here](https://anope.org/docgen/1.8/en_us/NickServ.html).  
The option to hide the email address is:

    /msg NickServ SET HIDE EMAIL ON

The option
    
    /msg NickServ SET PRIVATE ON

hide nickname lists generated with NickServ's LIST command.  
I will update the wiki, thanks you

**Comment by RealKindOne** [comment]
freenode uses atheme, not anope. 

https://github.com/atheme/atheme/wiki/NickServ%3ASET%3AHIDEMAIL

https://github.com/atheme/atheme/wiki/NickServ%3ASET%3APRIVATE

https://atheme.github.io/atheme.html

freenode automatically hides the email address when registering an account. 

Setting ` ` ` PRIVATE` ` `  would only be useful for obscuring the last seen/user seen info, not hide the email address that is already hidden by default on freenode.

**Comment by szorfein** [comment]
ok thanks you, i have update the instruction for create the right certificate with `ecdsa-nist256p-challenge` too

**Comment by RealKindOne** [comment]
Thanks.
